apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: whodat-service
  title: Whodat Service
  description: |
    This repo contains the code for the 'whodat' service which is used
    to amend matches for invalid national identity numbers.
  tags:
    - kotlin
    - micronaut
    - docker
  annotations:
    github.com/project-slug: statisticsnorway/whodat-service
spec:
  type: service
  owner: dapla-stat-developers
  lifecycle: production
