guardian:
  mp-client-id: ${MP_CLIENT_ID}
keycloak:
  gcp-client-project-id: ${GCP_KEYCLOAK_CLIENTS_PROJECT_ID}
  gcp-client-team-uniform-name: dapla-stat
  keycloak-url: auth.test.ssb.no

micronaut:
  netty:
    event-loops:
      default:
        loom-carrier: true
      http-client:
        loom-carrier: true
        num-threads: 100
  http:
    client:
      pool:
        connection-locality: enforced-always
      event-loop-group: http-client
      read-timeout: 20s
    services:
      cloud-identity-service:
        url: https://cloudidentity.googleapis.com
        path: '/v1'
        read-timeout: 60s
      keycloak:
        url: https://auth.test.ssb.no/
        read-timeout: 60s
      maskinporten:
        url: https://guardian.intern.test.ssb.no/
        read-timeout: 60s
      freg:
        url: https://folkeregisteret-api-konsument.sits.no/
        read-timeout: 60s

  caches:
    cloud-identity-service-cache:
      expire-after-write: 30s

  security:
    token:
      jwt:
        signatures:
          jwks:
            keycloak-nais-test:
              url: 'https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs'
            lab-id-north1-test:
              url: 'https://labid.lab.dapla-test-external.ssb.no/jwks'
            lab-id-north1-dev:
              url: 'https://labid.lab.dapla-dev-external.ssb.no/jwks'
            google:
              url: 'https://www.googleapis.com/oauth2/v3/certs'

gcp:
  http:
    client:
      filter:
        project-id: ${DAPLA_STAT_PROJECT_ID}
        services:
          cloud-identity-service:
            scopes:
              - "https://www.googleapis.com/auth/cloud-identity.groups.readonly"

app-roles:
  trusted-issuers:
    - 'https://labid.lab.dapla-dev-external.ssb.no'
    - 'https://labid.lab.dapla-test-external.ssb.no'
    - 'https://auth.test.ssb.no/realms/ssb/protocol/openid-connect/certs'
  user-group-names:
    - 'whodat-service-m2m-t@ssb.no'
    - 'whodat-service-user-t@ssb.no'