micronaut:
  application:
    name: whodat-service
  server:
    port: 9191
    netty:
      logLevel: TRACE
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
    logger:
      levels:
        no.ssb.whodat.service: INFO
        io.micronaut.security: INFO
        io.micronaut.security.token.jwt.validator: DEBUG
    openapi:
      views:
        spec: |
          mapping.path=classpath:META-INF/swagger,
          swagger-ui.enabled=true,
          swagger-ui.js.url=/swagger-ui/res/,
          swagger-ui.tagsSorter=Function=(a => a),
  security:
    enabled: true
    intercept-url-map:
      - pattern: /swagger-ui/**
        httpMethod: GET
        access: isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access: isAnonymous()
      - pattern: /health/**
        http-method: GET
        access: isAnonymous()
      - pattern: /metrics/**
        http-method: GET
        access: isAnonymous()
      - pattern: /prometheus/**
        http-method: GET
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()

    token:
      name-key: email
      jwt:
        signatures:
          jwks-client:
            http-client:
              enabled: false

    basic-auth:
      enabled: false

endpoints:
  all:
    port: 9191
  environments:
    enabled: true
    sensitive: false
  health:
    sensitive: false
    details-visible: ANONYMOUS
    service-http-client:
      enabled: true
    monitor:
      enabled: true

logger:
  config: logback.xml