# Dependencies referenced in build.gradle.kts
# See https://docs.gradle.org/current/userguide/platforms.html

# Each block is sorted alphabetically.

[versions]
caffeineCache = "3.2.3"
cyclonedx = "2.3.1"
gradleShadow = "9.4.1"
jackson = "2.21.1"
jib = "3.4.5"
kotlin = "2.2.21"
kotlinxCoroutines = "1.10.2"
ksp = "2.3.0"
ktlint = "14.2.0"
logback = "1.5.32"
netty = "4.2.12.Final"
micronaut = "4.10.10"
micronautAop = "4.10.18"
micronautCache = "5.3.0"
micronautGcp = "5.12.0"
micronautGradle = "4.6.2"
micronautManagement = "4.10.7"
micronautMicrometer = "5.12.0"
micronautKotlin = "4.7.0"
micronautOpenapi = "6.20.0"
micronautSecurity = "4.18.0"
micronautSerde = "2.16.1"
micronautTest = "4.10.1"
micronautValidation = "4.10.0"
snakeyaml = "2.4"
reactor = "3.7.12"
ulidKotlin = "1.5.0"
mockk="1.13.2"
micronautRetry="4.10.3"
mockwebserver="4.12.0"
kotlinxCoroutinesTest="1.8.1"


[libraries]
caffeine-cache = {module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeineCache"}
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinxCoroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micronaut-kotlin-runtime = { module = "io.micronaut.kotlin:micronaut-kotlin-runtime", version.ref = "micronautKotlin" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client", version.ref = "micronaut" }
micronaut-http-validation = { module = "io.micronaut:micronaut-http-validation", version.ref = "micronaut" }
micronaut-management = { module = "io.micronaut:micronaut-management", version.ref = "micronautManagement" }
micronaut-micrometer-registry-prometheus = { module = "io.micronaut.micrometer:micronaut-micrometer-registry-prometheus", version.ref = "micronautMicrometer" }
micronaut-openapi = { module = "io.micronaut.openapi:micronaut-openapi", version.ref = "micronautOpenapi" }
micronaut-openapi-annotations = { module = "io.micronaut.openapi:micronaut-openapi-annotations", version.ref = "micronautOpenapi" }
micronaut-security-jwt = { module = "io.micronaut.security:micronaut-security-jwt", version.ref = "micronautSecurity" }
micronaut-security-annotations = { module = "io.micronaut.security:micronaut-security-annotations", version.ref = "micronautSecurity" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson", version.ref = "micronautSerde" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor", version.ref = "micronautSerde" }
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
micronaut-gcp-common = { module = "io.micronaut.gcp:micronaut-gcp-common", version.ref = "micronautGcp" }
micronaut-gcp-secret-manager = { module = "io.micronaut.gcp:micronaut-gcp-secret-manager", version.ref = "micronautGcp" }
micronaut-cache-core = { module = "io.micronaut.cache:micronaut-cache-core", version.ref = "micronautCache" }
micronaut-cache-caffeine = { module = "io.micronaut.cache:micronaut-cache-caffeine", version.ref = "micronautCache" }
micronaut-aop = { module = "io.micronaut:micronaut-aop", version.ref = "micronautAop" }
micronaut-retry = { module = "io.micronaut:micronaut-retry", version.ref = "micronautRetry" }
reactor = { module = "io.projectreactor:reactor-core", version.ref = "reactor" }
ulid-kotlin = { module = "com.aallam.ulid:ulid-kotlin", version.ref = "ulidKotlin" }
mockk = { module = "io.mockk:mockk", version = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }


[plugins]
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronautGradle" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronautGradle" }
micronaut-test-resources = { id = "io.micronaut.test-resources", version.ref = "micronautGradle" }
micronaut-openapi = { id = "io.micronaut.openapi", version.ref = "micronautGradle" }
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradleShadow" }
