# Dependencies referenced in build.gradle.kts
# See https://docs.gradle.org/current/userguide/platforms.html

# Each block is sorted alphabetically.

[versions]
cyclonedx = "2.3.1"
gradleShadow = "8.3.6"
jackson = "2.19.2"
jib = "3.4.5"
kotlin = "2.2.10"
kotlinxCoroutines = "1.8.1"
ksp = "2.2.10-2.0.2"
ktlint = "13.0.0"
logback = "1.5.18"
micronaut = "4.9.2"
micronautGcp = "5.12.0"
micronautGradle = "4.5.4"
micronautMicrometer = "5.12.0"
micronautKotlin = "4.7.0"
micronautOpenapi = "6.17.3"
micronautSecurity = "4.13.1"
micronautSerde = "2.15.1"
micronautTest = "4.8.1"
micronautValidation = "4.10.0"
snakeyaml = "2.4"

[libraries]
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micronaut-kotlin-runtime = { module = "io.micronaut.kotlin:micronaut-kotlin-runtime", version.ref = "micronautKotlin" }
micronaut-http-client = { module = "io.micronaut:micronaut-http-client", version.ref = "micronaut" }
micronaut-http-validation = { module = "io.micronaut:micronaut-http-validation", version.ref = "micronaut" }
micronaut-micrometer-registry-prometheus = { module = "io.micronaut.micrometer:micronaut-micrometer-registry-prometheus", version.ref = "micronautMicrometer" }
micronaut-openapi = { module = "io.micronaut.openapi:micronaut-openapi", version.ref = "micronautOpenapi" }
micronaut-openapi-annotations = { module = "io.micronaut.openapi:micronaut-openapi-annotations", version.ref = "micronautOpenapi" }
micronaut-security-jwt = { module = "io.micronaut.security:micronaut-security-jwt", version.ref = "micronautSecurity" }
micronaut-security-annotations = { module = "io.micronaut.security:micronaut-security-annotations", version.ref = "micronautSecurity" }
micronaut-serde-jackson = { module = "io.micronaut.serde:micronaut-serde-jackson", version.ref = "micronautSerde" }
micronaut-serde-processor = { module = "io.micronaut.serde:micronaut-serde-processor", version.ref = "micronautSerde" }
snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }
micronaut-gcp-common = { module = "io.micronaut.gcp:micronaut-gcp-common", version.ref = "micronautGcp" }
micronaut-gcp-secret-manager = { module = "io.micronaut.gcp:micronaut-gcp-secret-manager", version.ref = "micronautGcp" }

[plugins]
allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
jib = { id = "com.google.cloud.tools.jib", version.ref = "jib" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
micronaut-aot = { id = "io.micronaut.aot", version.ref = "micronautGradle" }
micronaut-application = { id = "io.micronaut.application", version.ref = "micronautGradle" }
micronaut-test-resources = { id = "io.micronaut.test-resources", version.ref = "micronautGradle" }
micronaut-openapi = { id = "io.micronaut.openapi", version.ref = "micronautGradle" }
gradle-shadow = { id = "com.gradleup.shadow", version.ref = "gradleShadow" }