name: Image Build and Deploy

on:
  release:
    types: [ published ]
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/build-and-deploy.yml'
  workflow_dispatch:
    inputs:
      cluster:
        description: "'prod' or 'test'"
        default: "test"

env:
  REGISTRY: europe-north1-docker.pkg.dev/${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}/dapla-stat
  DOCKER_IMAGE: europe-north1-docker.pkg.dev/${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}/dapla-stat/whodat-service:${{ github.sha }}
  DOCKER_IMAGE_WITHOUT_TAG: europe-north1-docker.pkg.dev/${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}/dapla-stat/whodat-service

jobs:
  docker-build:
    name: Docker build
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    outputs:
      nais_cluster: ${{ steps.nais-deploy-vars.outputs.nais_cluster }}
      nais_config_path: ${{ steps.nais-deploy-vars.outputs.nais_config_path }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set nais environment variables
        id: nais-deploy-vars
        run: |
          cluster_manual_deploy=${{inputs.cluster}}
          if [[ ${{ github.event_name }} == "release" || ${cluster_manual_deploy} == "prod" ]]; then
            echo "nais_cluster=prod" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/prod/nais.yaml" >> "$GITHUB_OUTPUT"
          else
            echo "nais_cluster=test" >> "$GITHUB_OUTPUT"
            echo "nais_config_path=.nais/test/nais.yaml" >> "$GITHUB_OUTPUT"
          fi

      - name: "Authenticate to Google Cloud"
        id: "auth"
        uses: "google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093" # v3.0.0
        with:
          workload_identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }} # Provided as Organization Secret
          service_account: "gh-ssb@${{ secrets.NAIS_MANAGEMENT_PROJECT_ID }}.iam.gserviceaccount.com"
          token_format: "access_token"

      - name: Login to registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{env.REGISTRY}}
          username: "oauth2accesstoken"
          password: "${{ steps.auth.outputs.access_token }}"

      - name: Set up Java
        uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version: 25
          distribution: "zulu"

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0

      - name: Build and push Docker image
        run: >
          ./gradlew
          cyclonedxBom
          jib
          --image=${{ env.DOCKER_IMAGE }}
          --daemon --parallel --build-cache

      - name: Set docker image env var
        run: |
          echo "DOCKER_IMAGE_DIGEST=$(cat build/jib-image.digest)" >> $GITHUB_ENV

      - name: "Attest and sign"
        uses: "nais/attest-sign@c839bd87ba71207e36341b6e9b6d8aabdcbc86c2" # v2.0.12
        with:
          image_ref: ${{ env.DOCKER_IMAGE_WITHOUT_TAG }}@${{ env.DOCKER_IMAGE_DIGEST }}
          # This SBOM includes all JVM dependencies (generated with cyclonedxBom) but does
          # not include other software installed in the image (e.g. OS libraries, tools).
          # A future improvement could be to generate this and merge the BOMs
          sbom: build/reports/bom.json

  deploy:
    name: Deploy to NAIS cluster
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    needs: docker-build
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ secrets.DAPLA_BOT_APP_ID }}
          private-key: ${{ secrets.DAPLA_BOT_PRIVATE_KEY }}
          owner: statisticsnorway
          repositories: dapla-stat-iac

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        name: Retrieve protected configuration
        with:
          repository: "statisticsnorway/dapla-stat-iac"
          ref: main
          path: "ext-config"
          token: ${{ steps.app-token.outputs.token }}
          sparse-checkout: |
            apps/nais/whodat-service/${{ needs.docker-build.outputs.nais_cluster }}

      - name: Configure environment variables
        run: |
          ext_config_dir="ext-config/apps/nais/whodat-service/${{ needs.docker-build.outputs.nais_cluster }}"
          echo "ext_config=${ext_config_dir}" >> $GITHUB_ENV

      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b # v2
        env:
          CLUSTER: ${{ needs.docker-build.outputs.nais_cluster }}
          RESOURCE: ${{ needs.docker-build.outputs.nais_config_path }},${{ env.ext_config }}/app-roles.yml
          VAR: image=${{ env.DOCKER_IMAGE }},team=dapla-stat
          DEPLOY_SERVER: deploy.ssb.cloud.nais.io:443
