
name: Run tests

on:
  push:
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/workflows/run-tests.yaml'

permissions:
  contents: read

jobs:
  build-branch:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: 25
          distribution: 'zulu'

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic

      - name: Build and test project
        run: >
          ./gradlew
          test
